name: Deploy Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Descargar el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ Configurar DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # 3️⃣ Construir imagen Docker
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend-test:latest .

    # 4️⃣ Push de la imagen a DockerHub
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend-test:latest

    # 5️⃣ Configurar kubeconfig
    - name: Configure Kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig

    # 6️⃣ Desplegar a Kubernetes
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deploy.yaml
        kubectl apply -f k8s/service.yaml
